#pragma config(Sensor, S1,     IRSeeker1,      sensorI2CCustom)
#pragma config(Sensor, S2,     IRSeeker2,      sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "C:\Program Files (x86)\Robomatter Inc\ROBOTC Development Environment 4.X\Sensor Drivers\include\hitechnic-irseeker-v2.h"
#define PARENT_IR_HIGH 7
#define PARENT_IR_LOW 2
#define CHILD_IR_LOW 3
#define CHILD_IR_HIGH 8

// Check out idea of primary & secondary seekers

void setup(){
	nxtDisplayTextLine(2, "IR TRIANGULATE");
	nxtDisplayTextLine(3, "IR1 = S1");
	nxtDisplayTextline(4, "IR2 = S2");
	wait1Msec(2000);
	eraseDisplay();
}
int IRTriangulate(long IRval1, long IRval2){
	if(IRval1 - PARENT_IR_LOW < 0 || IRval1 - PARENT_IR_LOW > PARENT_IR_HIGH - PARENT_IR_LOW){
		return -1; // BAD READING //
	}
	if(IRval2 - CHILD_IR_LOW < 0 || IRval2 - CHILD_IR_LOW > CHILD_IR_HIGH - CHILD_IR_LOW){
		return -1; // BAD READING //
	}
	return (IRval1 - PARENT_IR_LOW) + (IRval2 - CHILD_IR_LOW);
}
task main()
{
	tHTIRS2 IR1;
	tHTIRS2 IR2;
	initSensor(&IR1, S1);
	initSensor(&IR2, S2);
	IR1.mode = DSP_1200;
	IR2.mode = DSP_1200;
	setup();
	while(true){
		readSensor(&IR1);
		readSensor(&IR2);
		nxtDisplayTextLine(2, "IR1 = %d", IR1.acDirection);
		nxtDisplayTextLine(3, "%d,%d,%d,%d,%d", IR1.acValues[0], IR1.acValues[1], IR1.acValues[2], IR1.acValues[3], IR1.acValues[4]);
		nxtDisplayTextLine(4, "IR2 = %d", IR2.acDirection);
		nxtDisplayTextLine(5, "%d,%d,%d,%d,%d", IR2.acValues[0], IR2.acValues[1], IR2.acValues[2], IR2.acValues[3], IR2.acValues[4]);
		nxtDisplayTextLine(6, "TRIA = %d", IRTriangulate(IR1.acDirection, IR2.acDirection));
		wait1Msec(100);
		eraseDisplay();
	}
}
